server:
  port: 3000

spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${db.host}:${db.port}:XE
    username: ${db.username}
    password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: update

  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

  # 정적 자원 설정(CSS, JS, 이미지)
  web:
    resources:
      staticLocations: file:src/main/resources/static/

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB
      fileSizeThreshold: 30MB


# 파일 업로드 경로 설정
file:
  upload:
    path: D:/uploads
    url: /upload/

# 로거 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace